### ISSUE TITLE
Hacer casos de uso (se agrego una tarea por cada uno)

### ISSUE THREAD

**Issue by comtom** [comtom/Atendeme#2]

**Comment by DeRegem** [comment]
![3 12 - insertar consulta en historia clinica](https://cloud.githubusercontent.com/assets/12282548/8067428/fd3542cc-0ec3-11e5-9240-020c3c31b028.JPG)

Nombre de Caso de Uso: Insertar Consulta en Historia Clínica.
Actores: Médico.
Descripción: El médico insertará una nueva consulta en una Historia Clínica.
Precondición: El médico debe estar logueado en el sistema y el paciente registrado.
Flujo básico:  El médico accede a la Historia Clínica del paciente a través de la lista de pacientes del día. El médico completa los campos "Motivo de la consulta", "Observaciones", "Medicación" y  "Estudios". Luego, confirma la inserción de la nueva consulta a la Historia Clínica.
Flujo alternativo: Si el médico no completa el campo de "Motivo de la consulta" el sistema le envía un mensaje de error.
Postcondición: Luego de confirmada la inserción de la consulta, la Historia Clínica se actualiza.

**Comment by DeRegem** [comment]
https://www.lucidchart.com/invitations/accept/fb892ec6-fbd1-420d-9cea-1581559b0493

Nombre de Caso de Uso: Logueo de Usuarios.
Actores: Administrador, Médico, Recepcionista, Paciente.
Descripción: El usuario accede al sistema.
Precondición: -.
Flujo básico: El usuario completa los campos "Nombre de usuario" y "Contraseña", luego confirma el acceso al sistema.
Flujo alternativo: Si el usuario no completa los campos de "Nombre de usuario" y/o "Contraseña", o si tras el chequeo de la información de la cuenta no hay matching, el sistema le envía un mensaje de error.
Postcondición: El sistema le da acceso al usuario según su tipo (Administrador, Médico, Recepcionista o Paciente).

**Comment by lhdani** [comment]
https://www.lucidchart.com/documents/edit/261a3671-c35a-4a1a-984e-486280ec9990/0

Nombre de Caso de Uso: Agregar usuario al sistema - Administrador.
Actores: Administrador, Médico, Recepcionista.
Descripción: El administrador agregara un nuevo usuario al sistema.
Precondición: El administrador debe estar logueado en el sistema.
Flujo básico: El administrador accede a la opción "Agregar usuario", luego se crea un nuevo registro en la tabla de Usuarios. El administrador completa con los datos del usuario el formulario, otorgando permisos según sea el tipo de usuario, luego se guardan los datos que corresponden al nuevo usuario.
Flujo alternativo: Si el administrador no completa alguno de los datos se mostrara un error. El sistema solicitará que se completen los datos
Postcondición: Luego de confirmada la inserción del usuario, este podrá ingresar al sistema.

**Comment by lhdani** [comment]
https://www.lucidchart.com/documents/edit/12e1e2ce-563f-4a93-886f-8c77a4e40d89?

Nombre de Caso de Uso: Calendario de Turnos.
Actores:Recepcionista.
Descripción: La recepcionista puede visualizar en un calendario los turnos "Disponibles" y los turnos "No Disponibles".
Pre-condición: La recepcionista debe estar logueada en el sistema.
Flujo básico: La recepcionista puede seleccionar "Ver calendario de turnos" para poder visualizar mediante un calendario los turnos que quedan disponibles y los turnos que no están disponibles.
Flujo alternativo:--
Post-condición: Luego de visualizar el calendario de turnos, la recepcionista podrá otorgar turnos según estos tengan asignado el estado "Disponible".
