### ISSUE TITLE
Modelo de objetos con objetos Entidades, de Interfaz y de Control

### ISSUE THREAD

**Issue by comtom** [comtom/Atendeme#31]
https://www.lucidchart.com/invitations/accept/724748e8-ec62-4eae-9a06-983b692b802b

**Comment by comtom** [comment]
Faltan algunos diagramas y separarlos en documentos distintos, para entregarlos

**Comment by lhdani** [comment]
Hago una pregunta. Estos diagramas llevan algún tipo de descripción??

**Comment by comtom** [comment]
No estoy seguro, habría que revisar en el Jacobson. Yo hice el gráfico de 3
o 4, si podes verificar que estén bien, los separamos en un doc cada uno y
los mandamos para q nos los corrijan los profesores.

El sáb, jul 18, 2015 02:30 PM, lhdani <notifications@github.com> escribió:

> Hago una pregunta. Estos diagramas llevan algún tipo de descripción??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/comtom/Atendeme/issues/31#issuecomment-122570760>.
>
-- 
Tomás Gonzalez Dowling | Comtom Tech

**Comment by comtom** [comment]
Ya dividi los graficos, les paso la url de los 4 documentos:

https://drive.google.com/open?id=0B8Ux34-slH6mfllRRlpNRU82X0o4T04ycGZCUE5lMW5DeDIyU21ra2ZfaXhUUG1UellXWFk

y del grafico por si hay que modificar algo:
https://www.lucidchart.com/documents/edit/ca5434b2-d2a0-4a70-baf3-2fdfe19dae1c

**Comment by comtom** [comment]
Falta completar el 1, 8, 13 y 15
